### ISSUE TITLE
minor bug in sueff

### ISSUE THREAD

**Issue by colasri** [ubccr/stubl#2]
Thanks for your scripts!
In line 67 of sueff: https://github.com/ubccr/stubl/blob/master/bin/sueff#L67
`if [ "memsum" != "" ]; then`
should be replace by
`if [ "$memsum" != "" ]; then`
Now, I need to start using cgroup...

**Comment by dsajdak** [comment]
This was fixed at some point.  Very sorry for not responding to your bug report.  Thank you!
